namespace: be-hcm-basic
replicaCount: 1
appName: hcm-sd-service
instance: sicix
timezone: Asia/Ho_Chi_Minh
dateFormat: yyyy-MM-dd'T'HH:mm:ssZ
apiKey: test
config:
  location: /ngs/config/
container:
  port: 8080
  image:
    repository: registry.xdp.vn:5000/hcm-sd-service
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  livenessProbe: |
    failureThreshold: 3
    initialDelaySeconds: 30
    periodSeconds: 2
    successThreshold: 1
    tcpSocket:
      port: {{ .Values.service.port }}
    timeoutSeconds: 2
  readinessProbe: |
    failureThreshold: 3
    initialDelaySeconds: 30
    periodSeconds: 2
    successThreshold: 2
    tcpSocket:
      port: {{ .Values.service.port }}
    timeoutSeconds: 2
  resources: { }

configMap:
  files:
    application:
      enable: false
      name: hcm-sd
      key: application.yml
      path: config/application.yml
      mountPath: /ngs/config/application.yml
      subPath: application.yml

database:
  name: nspace
  address: 172.16.101.39
  port: 5432
  schema: hcm_sd_service
  username: xdp
  password: gjEyCJRruMz28kw96OWXy5JBN9pOROXT

redis:
  host: 172.16.101.36
  port: 6379

queue:
  kafka: 172.16.101.36:9092
  zookeeper: 172.16.101.36:2181

service:
  name: tcp
  type: ClusterIP
  port: 8080

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: { }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: { }

podSecurityContext: { }
# fsGroup: 2000

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 90
podAntiAffinity:
  enabled: true
nodeSelector: { }

tolerations: [ ]

affinity:
  podAntiAffinity:
    preferred: true
